version: '3.1'
services:
  web:
    build: docker/python
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - .:/project:rw
  db:
    image: postgres:10.3-alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=django