# Generated by Django 2.1.3 on 2018-11-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'Available'), (2, 'Busy')], default=1, max_length=1, verbose_name='Status')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
