# Generated by Django 2.1.3 on 2018-11-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20181109_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.IntegerField(choices=[(1, 'Disponível'), (2, 'Ocupado')], default=1, verbose_name='Estado'),
        ),
    ]
