# Generated by Django 2.1.3 on 2018-11-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20181109_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduling',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='end_date',
            field=models.DateTimeField(verbose_name='Data de fim'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='start_date',
            field=models.DateTimeField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Nome do usuário'),
        ),
    ]
