name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.4.0
      with:
        compose-file: "./docker/docker-compose.yml"
        down-flags: "--volumes"
    - name: Test Django
      run: docker-compsoe exec web app/manage.py test
