name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.4.0
      with:
        compose-file: "docker-compose.yml"
        up-flags: "--build"
        down-flags: "--volumes"
        compose-flags: "exec web python3 app/manage.py test"
        services: |
          web
          db
